  ruoyi-server1:
    image: ruoyi/ruoyi-server:5.1.0
    container_name: ruoyi-server1
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SERVER_PORT: 8080
    volumes:
      # 配置文件
      - /docker/server1/:/ruoyi/server/
      # skywalking 探针
    #      - /docker/skywalking/agent/:/ruoyi/skywalking/agent
    privileged: true
    network_mode: "host"